name: COMPAS compile test

on: [pull_request]
    # branches: [dev]
    # paths: ['main/**'] # only changes to src/ trigger this workflow
  # push: 
    # branches: [dev]
    # paths: ['main/**']

jobs:
  compas:
    name: Build COMPAS
    runs-on: ${{ matrix.os}}
    # container: ${{matrix.container}}  # to run the job on centos 7 docker image which runs on ubuntu-18.04 machine
    strategy:
      fail-fast: false  #in case build failed on one of the runners, it won't stop building on other runners
      matrix:
        os: [macos-latest]  # runners(virtual machines) to run the job on
        # include: # add the combination to run the centos container only on ubuntu-18.04
        #   - os: ubuntu-18.04
        #     container: 'centos:7'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Cache Homebrew Packages
        id: cache-homebrew-packages
        uses: actions/cache@v3
        env:
          cache-name: homebrew-packages
        with:
          path: $(brew --prefix)
          key: ${{ matrix.os }}-${{ env.cache-name }}-${{ hashFiles('.config/brew/Brewfile') }}
        if: startsWith(matrix.os, 'macos')

      # - name: Clean Homebrew Packages
      #   run: brew list --formula | xargs -n1 brew uninstall -f --ignore-dependencies && rm $(brew --prefix)/bin/{aws,aws_completer,conda}
      #   if: startsWith(matrix.os, 'macos') && steps.cache-homebrew-packages.outputs.cache-hit != 'true'


      # This step will run only on ubuntu-20.04
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu-20') 
        run: |
          cd utils/cicd-scripts
          chmod 755 linux-dependencies
          ./linux-dependencies
      # This step will run only on centos 7 container on ubuntu-18.04
      - name: Install dependencies on centos docker container
        if: startsWith(matrix.container, 'centos')
        run: |
          cd utils/cicd-scripts
          chmod 755 centos-dependencies
          ./centos-dependencies
      
      # This step will run only on macos
      - name: Install dependencies on macos
        if: startsWith(matrix.os, 'macos')
        run: |
          cd utils/cicd-scripts
          chmod 755 macos-dependencies
          ./macos-dependencies
      # This step will run only on all runners
      # **To be investgated further** COMPAS doesn't build on Centos
      - name: Build Compas
        run: |
          cd src && make -j $(nproc) -f Makefile
          ./COMPAS -v
        env:
          nproc: 4

      # This step will run only on all runners
      - name: Install Python packages
        run: |
          pip install -r requirements.txt
      # This step will run on all runners
      # **To be investigated further** plotting script is currently failing on macos because 
      # for some reason it cannot recognise latex is installed
      - name: Run Post-Processing Python Scripts
        # if: startsWith(matrix.os, 'ubuntu-20') || startsWith(matrix.os, 'ubuntu-18')
        run: |
          cd utils/cicd-scripts
          chmod 755 python-scripts
          ./python-scripts
          